# Generated by Django 3.1 on 2020-09-11 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_name', models.CharField(max_length=100)),
                ('sets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sets', serialize=False, to='activity.exerciseset', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrengthSection',
            fields=[
                ('name', models.TextField(blank=True)),
                ('section_name', models.CharField(max_length=100)),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='exercise', serialize=False, to='activity.exercise', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_type', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('strength', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='strength', serialize=False, to='activity.strengthsection', unique=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
