# Generated by Django 3.1 on 2020-10-08 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('cardio_type', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('STRENGTH', 'STRENGTH'), ('CARDIO', 'CARDIO')], default='STRENGTH', max_length=30),
        ),
        migrations.AlterField(
            model_name='activity',
            name='strength',
            field=models.ManyToManyField(blank=True, related_name='exercise', to='activity.StrengthSections'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.ManyToManyField(blank=True, related_name='exercise_set', to='activity.ExerciseSet'),
        ),
        migrations.AlterField(
            model_name='strengthsections',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='exercise', to='activity.Exercise'),
        ),
        migrations.AddField(
            model_name='activity',
            name='cardio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.cardiosession'),
        ),
    ]
