# Generated by Django 3.1 on 2020-09-05 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_posted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrengthSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('exercises', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.exerciseset'),
        ),
        migrations.CreateModel(
            name='CardioSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('exercises', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='cardio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.cardiosection'),
        ),
        migrations.AddField(
            model_name='activity',
            name='strength',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.strengthsection'),
        ),
    ]
