# Generated by Django 3.1 on 2020-09-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20200905_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiosection',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='strengthsection',
            name='exercises',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseSet',
        ),
    ]
