# Generated by Django 3.1 on 2020-09-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20200905_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='cardio',
            new_name='CardioSection',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='strength',
            new_name='StrengthSection',
        ),
    ]
