# Generated by Django 3.1 on 2020-10-09 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20201008_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='strengthsections',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exercise',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.strengthsections'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.exercise'),
        ),
        migrations.AddField(
            model_name='strengthsections',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.activity'),
        ),
    ]
