# Generated by Django 3.1 on 2020-09-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20200905_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='CardioSection',
            new_name='cardio',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='StrengthSection',
            new_name='strength',
        ),
    ]
