# Generated by Django 3.1 on 2020-10-09 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20201009_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='activity.strengthsections'),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='activity.exercise'),
        ),
    ]
