# Generated by Django 3.1 on 2020-09-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20200905_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='cardio',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='strength',
        ),
    ]
