# Generated by Django 3.1 on 2020-10-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20201009_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
