# Generated by Django 3.1 on 2020-09-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20200905_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cardio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.cardiosection'),
        ),
        migrations.AddField(
            model_name='activity',
            name='strength',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.strengthsection'),
        ),
    ]
