# Generated by Django 3.1 on 2020-09-05 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20200905_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cardio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardio', to='activity.cardiosection'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='strength',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strength', to='activity.strengthsection'),
        ),
    ]
