# Generated by Django 3.1 on 2020-09-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20200905_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='cardio',
        ),
        migrations.AddField(
            model_name='strengthsection',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='CardioSection',
        ),
    ]
