# Generated by Django 3.1 on 2020-09-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20200906_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='strength',
        ),
    ]
